### ISSUE TITLE
换个视频没法带上口罩。。。

### ISSUE THREAD

**Issue by jiaochunyu** [yangzhongke/ApplyMasksForWorldCup#1]
铁子，run起来了，但是没法替换上口罩，
能提供下原视频么，疯狂学习中，感谢~

**Comment by yangzhongke** [comment]
原视频删了，你就在网上随便搜一些没带口罩的视频下载就行了

**Comment by jiaochunyu** [comment]
> 原视频删了，你就在网上随便搜一些没带口罩的视频下载就行了

ok。我在探索下
